name: navtalk_flutter
description: Flutter sample client for NavTalk real-time digital human platform.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.11.6
  web_socket_channel: ^2.4.0
  http: ^1.2.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  sound_stream: ^0.4.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
